<?php

/**
 * @file
 * Valghalla_synch_node_export.module.
 */

/**
 * Implements hook_node_export_dependency_alter().
 */
function valghalla_synch_node_export_node_export_dependency_field_alter(&$handled, &$node, $dependency) {
  if (is_array($handled)) {
    foreach ($handled as $key => $element) {
      // Adding parent uuid, if not set already.
      if (!isset($handled[$key]['parent_uuid'])) {
        $handled[$key]['parent_uuid'] = $dependency->uuid;
      }
    }
  }
}

/**
 * Implements hook_node_export_import_alter().
 *
 * Updates the references inside $node->node_export_dependency
 * to the local created objects.
 */
function valghalla_synch_node_export_node_export_import_alter(&$nodes, $format, $save) {
  foreach ($nodes as $node) {
    if (isset($node->node_export_dependency)) {
      $field_collection_items = array();
      // Find all field_collection_items.
      foreach ($node->node_export_dependency as $dep_key => $dependency) {
        if (isset($dependency['type']) && strcmp($dependency['type'], 'field_collection_item') === 0) {
          $field_collection_items[$dependency['uuid']] = $dep_key;
        }
      }

      foreach ($node->node_export_dependency as $dep_key => $dependency) {
        // If element has a different parent uuid than node.
        // This means it's not node's direct child.
        if (isset($dependency['type']) && isset($dependency['parent_uuid']) && strcmp($dependency['parent_uuid'], $node->uuid) !== 0) {
          unset($node->node_export_dependency[$dep_key]);

          // Try to find a parent.
          $parent_dep_key = $field_collection_items[$dependency['parent_uuid']];
          if (isset($parent_dep_key)) {
            // Find if that entity exists already.
            $entity_ids = entity_get_id_by_uuid($dependency['type'], array($dependency['uuid']));
            $entity_id = $entity_ids ? reset($entity_ids) : FALSE;

            // Finally set the value.
            if ($entity_id) {
              $node->node_export_dependency[$parent_dep_key]['node_export_field_collection_data'][$dependency['field_name']][$dependency['langcode']][$dependency['delta']][$dependency['property']] = $entity_id;
            }
          }
        }
      }
    }
  }
}
