<?php

/**
 * @file
 * Valghalla synch node export install.
 */

/**
 * Implements hook_update_N().
 *
 * Enables field_collection_deploy and toggles off 'field_collection' module from
 * node_export_dependency.
 */
function valghalla_synch_node_export_update_7101() {
  module_enable(array(
    'field_collection_deploy',
  ));

  variable_set('node_export_dependency_disable_modules', array('field_collection' => 'field_collection'));
}
