<?php
/**
 * @file
 * valghalla_election.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function valghalla_election_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_bogstav'.
  $field_bases['field_bogstav'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_bogstav',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 1,
    ),
    'translatable' => 1,
    'type' => 'text',
  );

  // Exported field_base: 'field_date'.
  $field_bases['field_date'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_date',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'date',
    'settings' => array(
      'cache_count' => 4,
      'cache_enabled' => 0,
      'granularity' => array(
        'day' => 'day',
        'hour' => 0,
        'minute' => 0,
        'month' => 'month',
        'second' => 0,
        'year' => 'year',
      ),
      'repeat' => 0,
      'timezone_db' => '',
      'todate' => '',
      'tz_handling' => 'none',
    ),
    'translatable' => 1,
    'type' => 'date',
  );

  // Exported field_base: 'field_election_mails_send'.
  $field_bases['field_election_mails_send'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_election_mails_send',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        0 => 'nej',
        1 => 'ja',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 1,
    'type' => 'list_boolean',
  );

  // Exported field_base: 'field_election_status'.
  $field_bases['field_election_status'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_election_status',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        0 => 'nej',
        1 => 'ja',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 1,
    'type' => 'list_boolean',
  );

  // Exported field_base: 'field_election_type'.
  $field_bases['field_election_type'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_election_type',
    'indexes' => array(
      'tid' => array(
        0 => 'tid',
      ),
    ),
    'locked' => 0,
    'module' => 'taxonomy',
    'settings' => array(
      'allowed_values' => array(
        0 => array(
          'vocabulary' => 'valgtype',
          'parent' => 0,
        ),
      ),
    ),
    'translatable' => 1,
    'type' => 'taxonomy_term_reference',
  );

  // Exported field_base: 'field_logo'.
  $field_bases['field_logo'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_logo',
    'indexes' => array(
      'fid' => array(
        0 => 'fid',
      ),
    ),
    'locked' => 0,
    'module' => 'image',
    'settings' => array(
      'default_image' => 0,
      'uri_scheme' => 'public',
    ),
    'translatable' => 1,
    'type' => 'image',
  );

  // Exported field_base: 'field_partinavn'.
  $field_bases['field_partinavn'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_partinavn',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 1,
    'type' => 'text',
  );

  // Exported field_base: 'field_partisek'.
  $field_bases['field_partisek'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_partisek',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 1,
    'type' => 'text',
  );

  // Exported field_base: 'field_polling_stations'.
  $field_bases['field_polling_stations'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_polling_stations',
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'views',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'view' => array(
          'args' => array(),
          'display_name' => 'entityreference_1',
          'view_name' => 'polling_stations',
        ),
      ),
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  // Exported field_base: 'field_ppsp_party'.
  $field_bases['field_ppsp_party'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_ppsp_party',
    'indexes' => array(
      'tid' => array(
        0 => 'tid',
      ),
    ),
    'locked' => 0,
    'module' => 'taxonomy',
    'settings' => array(
      'allowed_values' => array(
        0 => array(
          'vocabulary' => 'partier',
          'parent' => 0,
        ),
      ),
    ),
    'translatable' => 0,
    'type' => 'taxonomy_term_reference',
  );

  // Exported field_base: 'field_ppsp_polling_station'.
  $field_bases['field_ppsp_polling_station'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_ppsp_polling_station',
    'indexes' => array(
      'nid' => array(
        0 => 'nid',
      ),
    ),
    'locked' => 0,
    'module' => 'node_reference',
    'settings' => array(
      'referenceable_types' => array(
        'absentee_ballot' => 0,
        'article' => 0,
        'constituency' => 0,
        'election' => 0,
        'email' => 0,
        'page' => 0,
        'panel' => 0,
        'polling_station' => 'polling_station',
        'roles' => 0,
        'volunteers' => 0,
      ),
      'view' => array(
        'args' => array(),
        'display_name' => '',
        'view_name' => '',
      ),
    ),
    'translatable' => 0,
    'type' => 'node_reference',
  );

  // Exported field_base: 'field_role_n1062'.
  $field_bases['field_role_n1062'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_role_n1062',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'valhalla_field_volunteers_roles',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'volunteers_roles_field',
  );

  // Exported field_base: 'field_role_n25'.
  $field_bases['field_role_n25'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_role_n25',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'valhalla_field_volunteers_roles',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'volunteers_roles_field',
  );

  // Exported field_base: 'field_role_n26'.
  $field_bases['field_role_n26'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_role_n26',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'valhalla_field_volunteers_roles',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'volunteers_roles_field',
  );

  // Exported field_base: 'field_role_n27'.
  $field_bases['field_role_n27'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_role_n27',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'valhalla_field_volunteers_roles',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'volunteers_roles_field',
  );

  // Exported field_base: 'field_role_n28'.
  $field_bases['field_role_n28'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_role_n28',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'valhalla_field_volunteers_roles',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'volunteers_roles_field',
  );

  // Exported field_base: 'field_role_n862'.
  $field_bases['field_role_n862'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_role_n862',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'valhalla_field_volunteers_roles',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'volunteers_roles_field',
  );

  // Exported field_base: 'field_role_n894'.
  $field_bases['field_role_n894'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_role_n894',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'valhalla_field_volunteers_roles',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'volunteers_roles_field',
  );

  // Exported field_base: 'field_role_n904'.
  $field_bases['field_role_n904'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_role_n904',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'valhalla_field_volunteers_roles',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'volunteers_roles_field',
  );

  // Exported field_base: 'field_secretary'.
  $field_bases['field_secretary'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_secretary',
    'indexes' => array(
      'uid' => array(
        0 => 'uid',
      ),
    ),
    'locked' => 0,
    'module' => 'user_reference',
    'settings' => array(
      'referenceable_roles' => array(
        2 => 0,
        3 => 0,
        4 => 4,
        5 => 0,
        6 => 0,
      ),
      'referenceable_status' => array(
        0 => 0,
        1 => 1,
      ),
      'view' => array(
        'args' => array(),
        'display_name' => '',
        'view_name' => '',
      ),
    ),
    'translatable' => 1,
    'type' => 'user_reference',
  );

  // Exported field_base: 'field_volunteers_pr_pol_st_party'.
  $field_bases['field_volunteers_pr_pol_st_party'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_volunteers_pr_pol_st_party',
    'indexes' => array(
      'revision_id' => array(
        0 => 'revision_id',
      ),
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'field_collection',
    'settings' => array(
      'hide_blank_items' => 1,
      'hide_initial_item' => 0,
      'path' => '',
    ),
    'translatable' => 0,
    'type' => 'field_collection',
  );

  return $field_bases;
}
