<?php
/*
 * @author Juulia Devadze <juulia@bellcom.ee>
 * @copyright Bellcom Open Source aps.
 */

function valhalla_settings_menu() {
  $items['admin/valghalla/settings'] = array(
    'title' => t('Settings'),
    'description' => t('General valghalla settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('valhalla_admin_settings_form'),
    'access arguments' => array('administer valghalla'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => -3,
  );
  return $items;
}

function valhalla_admin_settings_form($form, &$form_state) {
  $form['valhalla_settings_polling_station_lock'] = array(
    '#type' => 'checkbox',
    '#title' => t('Lås valgsteds opsætningen'),
    '#default_value' => variable_get('valhalla_settings_polling_station_lock', FALSE),
  );

  //
  // Let the admin select who should see the address fields on the edit form.
  $form['valhalla_settings_hide_address_fields'] = array(
    '#type' => 'radios',
    '#title' => t('Skjul adresse felter på deltager redigeringsformular.'),
    '#options' => array(
      0 => t('Vis for alle'),
      1 => t('Skjul for alle'),
      2 => t('Vis kun for administrator (roller med tilladelsen "Administerer valghalla")'),
    ),
    '#default_value' => variable_get('valhalla_settings_hide_address_fields', 0),
  );

  // Municipality. You can add people only from this municipality.
  $form['valhalla_settings_municipality'] = array(
    '#type' => 'select',
    '#title' => 'Municipality',
    '#options' => odin_get_municipalities(),
    '#default_value' => variable_get('valhalla_settings_municipality', 0),
  );

  // Chose which role is the 'Partisekretær'
  $form['valhalla_settings_party_secretary_role_id'] = array(
    '#title' => t('Vælg hvilken rolle, som er "Partisekretær"'),
    '#type' => 'select',
    '#options' => user_roles(TRUE),
    '#default_value' => variable_get('valhalla_settings_party_secretary_role_id'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_form_alter().
 */
function valhalla_settings_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'user_profile_form'){

    $form['field_polling_station']['#disabled'] = TRUE;

    if (user_access('administer valghalla')) {
      $form['field_polling_station']['#disabled'] = FALSE;
    }
  }

  if (variable_get('valhalla_settings_polling_station_lock', FALSE)) {
    _valhalla_settings_lock_field($form, $form_state);
  }

  // Hide the address fields for on the volunteer according to settings.
  if ($form_id == 'volunteers_node_form') {
    $fields = array(
      'field_address_road',
      'field_address_road_no',
      'field_address_floor',
      'field_address_door',
      'field_address_zipcode',
      'field_address_city',
      'field_address_coname',
    );

    $user_access = user_access('administer valghalla');
    $hide_address_field = variable_get('valhalla_settings_hide_address_fields', 0);

    switch ($hide_address_field) {
      case 0:
        $show_fields = TRUE;
        break;

      case 1:
        $show_fields = FALSE;
        break;

      case 2:
        $show_fields = TRUE;
        if (!$user_access) {
          $show_fields = FALSE;
        }
        break;
    }

    if (!$show_fields) {
      foreach ($fields as $field) {
        $form[$field]['#access'] = FALSE;
      }
    }
  }
}

function _valhalla_settings_lock_field(&$form, &$form_state) {
  $locked_fields = array('field_venue_teams', 'field_venue_team_members');
  foreach ($locked_fields as $field) {
    $lang = $form[$field]['#language'];
    $form[$field][$lang][0]['value']['#disabled'] = TRUE;
  }

  if ($form['#form_id'] === 'field_collection_item_form' && $form['#bundle'] === 'field_volunteers_pr_pol_st_party') {
    $roles = odin_get_roles();

    foreach ($roles as $role_id => $role) {
      $form["field_role_n" . $role_id]['#disabled'] = TRUE;
      $form["field_role_n" . $role_id]['#disabled'] = TRUE;
    }
  }
}
