<?php

/**
 * Implements hook_menu()
 */
function os2intra_simplesaml_menu() {
  $items = array();

  $items['admin/config/os2intra/simplesaml'] = array(
    'title'            => 'OS2Intra SimpleSAML',
    'description'      => 'Administer SimpleSAML',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os2intra_simplesaml_settings_form'),
    'access arguments' => array('administer os2intra simplesaml')
  );

  return $items;
}

/**
 * Form callback for settings
 */
function os2intra_simplesaml_settings_form($form, &$form_state) {
  $form['os2intra_simplesaml_simplesaml_enable'] = array(
    '#title' => t('Enabled SimpleSAML redirect'),
    '#type' => 'checkbox',
    '#default_value' => variable_get('os2intra_simplesaml_simplesaml_enable'),
  );
  $form['os2intra_simplesaml_redirected_ips'] = array(
    '#title'         => t('Redirect IP\'s to SimpleSAML login'),
    '#type'          => 'textfield',
    '#description'   => t('Comma separated. Ex. 192.168.1.1,192.168.2.1'),
    '#default_value' => variable_get('os2intra_simplesaml_redirected_ips')
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save',
  );

  return $form;
}

/**
 * Implements hook_form_validate().
 */
function os2intra_simplesaml_settings_form_validate($form, &$form_state) {
  if (preg_match("/[^0-9.,]/", $form_state['values']['os2intra_simplesaml_redirected_ips'])) {
    form_set_error('os2intra_simplesaml_redirected_ips', 'Invalid format');
  }
}

/**
 * Implements hook_form_submit().
 */
function os2intra_simplesaml_settings_form_submit($form, &$form_state) {
  variable_set('os2intra_simplesaml_redirected_ips', $form_state['values']['os2intra_simplesaml_redirected_ips']);
  variable_set('os2intra_simplesaml_simplesaml_enable', $form_state['values']['os2intra_simplesaml_simplesaml_enable']);
}

/**
 * Implements hook_user_login().
 *
 * Updates the user's LOOP account details.
 */
function os2intra_simplesaml_user_login(&$edit, $account) {
  $attributes = simplesamlphp_auth_get_attributes();

#  if (!empty($attributes)) {
#    if (isset($attributes['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname'])) {
#      $edit['field_name_first'][LANGUAGE_NONE][0]['value'] = $attributes['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname'];
#    }
#    if (isset($attributes['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname'])) {
#      $edit['field_name_last'][LANGUAGE_NONE][0]['value'] = $attributes['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname'];
#    }
#    if (isset($attributes['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'])) {
#      $edit['mail'] = $attributes['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'];
#    }
#    user_save($account, $edit);
#  }
}

/**
 * Implements hook_init().
 */
function os2intra_simplesaml_init() {
  // Do not run this from CLI.
  // Only proceed if user is NOT logged in and is NOT using drush uli for admin.
  if (php_sapi_name() != 'cli' && $GLOBALS['user']->uid == 0 && strpos($_GET['q'], 'user/reset/1') !== 0) {
    $custom_ips = array();
    $remote_ip = ip_address();
    if (variable_get('os2intra_simplesaml_simplesaml_enable')) {
      $simplesaml_redirect = FALSE;
      $redirected_ips = variable_get('os2intra_simplesaml_redirected_ips');

      if (empty($redirected_ips)) {
        // No redirect IPs set, then redirect for all IPs.
        $simplesaml_redirect = TRUE;
      }
      else {
        $custom_ips = explode(',', $redirected_ips);

        // If the client request is from one of the IP's, login using
        // SimpleSAMLphp; otherwise use nemid login.
        //
        // Check performed on parts of the ip address.
        // This makes it possible to add only the beginning of the IP range.
        // F.ex. 192.168 will allow all ip addresses including 192.168 as part
        // of the it.
        foreach ($custom_ips as $custom_ip) {
          if (strpos($remote_ip, $custom_ip) !== FALSE) {
            $simplesaml_redirect = TRUE;
            break;
          }
        }
      }

      if ($simplesaml_redirect && module_exists('simplesamlphp_auth')) {
        $non_redirect_paths = array(
          'saml_login',
          'user/logout',
          'user/login',
          'logout',
        );
        if (!in_array($_GET['q'], $non_redirect_paths)) {
          drupal_goto('saml_login', array('query' => drupal_get_destination()));
        }
      }
    }
  }
}
