<?php
/**
 * @file
 * Valhalla blocks module
 *
 * @author Thomas Thune Hansen <tth@bellcom.dk>
 * @copyright Bellcom Open Source aps.
 *
 * This module is responsible for the overview/status blocks.
 *  - These blocks are fetched asynchronously. The 2 Drupal
 *    blocks just insert a placeholder to be filled out, and
 *    instansiate rendering of the markup.
 * As well as the change election and change party blocks.
 *  - These 2, do not rely on the frontpage, and can be used
 *    wherever.
 */

/**
 * Implements hook_block_info().
 */
function valhalla_blocks_block_info() {
  return array(
    'party_status' => array(
      'info' => t('Parti status'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'party_constituency_status' => array(
      'info' => t('Valgkredsstatus'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_menu().
 */
function valhalla_blocks_menu() {
  $items['valhalla_blocks/ajax/view'] = array(
    'page callback' => 'valhalla_block_ajax_view',
    'access callback' => 'user_is_logged_in',
  );

  return $items;
}

/**
 * Implements hook_block_view().
 */
function valhalla_blocks_block_view($delta = '') {
  switch ($delta) {
    // The other blocks are fetched with AJAX. this is just simple markup to
    // fill.
    case 'party_status':
    case 'party_constituency_status':

      if ($_SESSION['election_nid']) {
        global $user;
        $cache = cache_get($delta . '_' . $user->uid . '_' . $_SESSION['election_nid']);

        $block_cache = $cache->data;
      }

      drupal_add_js(drupal_get_path('module', 'valhalla_blocks') . '/js/valhalla_blocks.js', 'file');

      $output = '<div id="valhalla_block-' . $delta . '" >
        <div class="progress progress-striped active">
          <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
            <span>Opdaterer</span>
            </div>
          </div>
          <div class="content">' . $block_cache . '</div>
        </div><script>valhalla_blocks.loadOverview("' . $delta . '");</script>';

      return array("content" => $output);
  }
}
/**
 * AJAX block view.
 *
 * Renders markup for the AJAX'ed blocks.
 */
function valhalla_block_ajax_view($delta = '') {
  $markup = '';
  global $user;

  $user_entity = user_load($user->uid);
  $user_party_id = empty($user_entity->field_party[LANGUAGE_NONE][0]['tid']) ? FALSE : $user_entity->field_party[LANGUAGE_NONE][0]['tid'];

  // Get polling stations user is allowed to see.
  $restrict_polling_stations = array();
  if (!empty ($user_entity->field_polling_station[LANGUAGE_NONE])) {
    foreach ($user_entity->field_polling_station[LANGUAGE_NONE] as $station) {
      $restrict_polling_stations[] = $station['nid'];
    }
  }

  // Users selected election is in $_SESSION['election_nid'].
  $election_node = node_load($_SESSION['election_nid']);

  if (!is_object($election_node)) {
    print 'Der er ikke valgt noget valg';
    return;
  }

  // We need to know what polling stations are active in this
  // election.
  $polling_stations_field = field_get_items('node', $election_node, 'field_polling_stations');

  foreach ($polling_stations_field as $data) {
    $polling_station_nids[$data['target_id']] = $data['target_id'];
  }

  if (empty($polling_station_nids)) {
    print 'Der er ingen valsteder på dette valg';
    return;
  }

  // We also need the roles.
  $roles = _valghalla_helper_get_roles();

  switch ($delta) {
    //
    // Party status (Overall).
    //
    case 'party_status':
      $count = odin_get_volunteers_count($_SESSION['election_nid'],
                                          $polling_station_nids,
                                          $roles,
                                          $user_party_id);
      $markup .= _valhalla_blocks_generate_overview_markup($count);
      break;

    //
    // Polling station status.
    //
    case 'party_constituency_status':
      $constituency_nids = array();

      // We need info on the polling station nodes (constituency)
      // So we just load them all.
      foreach (node_load_multiple($polling_station_nids) as $polling_station) {
        // If the array of restricting stations is not empty we only let the
        // user see the polling stations in this array.
        if (!empty($restrict_polling_stations) &&
           !in_array($polling_station->nid, $restrict_polling_stations)) {
          continue;
        }

        $polling_station_nid = $polling_station->nid;

        $constituency_field = field_get_items('node', $polling_station, 'field_constituency');
        $constituency_nids[$constituency_field[0]['nid']][$polling_station_nid] = $polling_station_nid;

        $polling_station_count[$polling_station_nid] = odin_get_volunteers_count(
                                                                          $_SESSION['election_nid'],
                                                                          array($polling_station_nid),
                                                                          $roles,
                                                                          $user_party_id);
      }
      $markup .= _valhalla_blocks_generate_constituency_markup($constituency_nids, $polling_station_count);

      break;
  }

  global $user;
  cache_set($delta . '_' . $user->uid . '_' . $_SESSION['election_nid'], $markup);

  print $markup;
}

/**
 * Generate overview markup.
 */
function _valhalla_blocks_generate_overview_markup($count) {
  $label = _valhalla_blocks_get_label($count['total_count']);
  $markup = '
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th class="column-label">I alt</th>
              <th class="column-label">Mangler</th>
            </tr>
          </thead>
          <tr>
            <td><div class="partistatusenhed">Status total</div></td>
            <td class="column-count ' . $label . '">' . $count['total_count']['total'] . '/' . $count['total_count']['assigned'] . '</td>
            <td class="column-count">' . ($count['total_count']['assigned'] - $count['total_count']['total']) . '</td>
          </tr>
          <tr>
            <td>Bekræftede</td>
            <td class="column-count">' . $count['total_count']['rsvp_ok'] . '</td>
            <td></td>
          </tr>
          <tr>
            <td>Afviste</td>
            <td class="column-count">' . $count['total_count']['rsvp_no'] . '</td>
            <td></td>
          </tr>
          <tr>
            <td>Afventer svar</td>
            <td class="column-count">' . ($count['total_count']['total'] - ($count['total_count']['rsvp_ok'] + $count['total_count']['rsvp_no'])) . '</td>
            <td></td>
          </tr>

        </table>';

  $markup .= '<table class="table">
                <thead>
                  <tr>
                    <th>Roller</th>
                    <th class="column-label">I alt</th>
                    <th class="column-label">Mangler</th>
                  </tr>
                </thead>';

  $roles = _valghalla_helper_get_roles();

  foreach ($count['role_count'] as $role_nid => $role_count) {
    $label = _valhalla_blocks_get_label($role_count);
    $markup .= '
        <tr>
          <td class="column-first">' . $roles[$role_nid] . '</td>
          <td class="column-count ' . $label . '">' . $role_count['total']
          . '/' . $role_count['assigned'] . '</td>
          <td class="column-count">' .
          ($role_count['assigned'] - $role_count['total']) . '</td>
        </tr>';
  }

  $markup .= '</table>';

  return $markup;
}

/**
 * Generates table markup for constituency.
 */
function _valhalla_blocks_generate_constituency_markup($constituency_nids, $polling_station_count) {
  $roles = _valghalla_helper_get_roles();

  $constituencies = array();

  foreach ($constituency_nids as $constituency_nid => $polling_station_nids) {
    $constituency_node = node_load($constituency_nid);
    $constituencies[$constituency_node->title] = $polling_station_nids;
  }

  ksort($constituencies);

  foreach ($constituencies as $constituency_title => $polling_station_nids) {
    $markup .= '<table class="table"><thead><tr><th>' . $constituency_title . '</th>';
    foreach ($roles as $role_nid => $role_title) {
      $markup .= '<th class="column-label">' . $role_title . '</th>';
    }

    $markup .= '<th class="column-label">I alt</th>';
    $markup .= '</tr></thead>';
    $markup .= _valhalla_blocks_generate_polling_station_markup($polling_station_nids,
                                                                $polling_station_count);
    $constituency_total = array();

    // Count constituency totals.
    foreach ($polling_station_count as $polling_station_nid => $data) {
      if (in_array($polling_station_nid, $polling_station_nids)) {
        $constituency_total['total_count']['assigned'] += $data['total_count']['assigned'];
        $constituency_total['total_count']['total'] += $data['total_count']['total'];
        $constituency_total['total_count']['rsvp_ok'] += $data['total_count']['rsvp_ok'];
        $constituency_total['total_count']['rsvp_no'] += $data['total_count']['rsvp_no'];

        foreach ($data['role_count'] as $role_nid => $role_count) {
          $constituency_total['role_count'][$role_nid]['assigned'] += $role_count['assigned'];
          $constituency_total['role_count'][$role_nid]['total'] += $role_count['total'];
          $constituency_total['role_count'][$role_nid]['rsvp_ok'] += $role_count['rsvp_ok'];
          $constituency_total['role_count'][$role_nid]['rsvp_no'] += $role_count['rsvp_no'];
        }
      }
    }

    $markup .= '<tr><td class="total">I alt</td>';

    // Generate bottom totals row.
    foreach ($roles as $role_nid => $role_title) {
      $label = _valhalla_blocks_get_label($constituency_total['role_count'][$role_nid]);

      $markup .= '<td class="total column-count ' . $label . ' ">' . $constituency_total['role_count'][$role_nid]['total'];
      $markup .= '/' . $constituency_total['role_count'][$role_nid]['assigned'] . '</td>';
    }
    $label = _valhalla_blocks_get_label($constituency_total['total_count']);

    $markup .= '<td class="total column-count ' . $label . ' ">' . $constituency_total['total_count']['total'];
    $markup .= '/' . $constituency_total['total_count']['assigned'] . '</td>';
    $markup .= '</tr>';
    $markup .= '</table>';
  }

  return $markup;
}

/**
 * Generates row markup for overview page.
 */
function _valhalla_blocks_generate_polling_station_markup($polling_station_nids, $polling_station_count) {
  $markup = '';

  // Preload all polling station nodes, get their weight.
  foreach ($polling_station_nids as $polling_station_nid) {
    $polling_station_node = node_load($polling_station_nid);

    $weight = 0;

    if ($field = field_get_items('node', $polling_station_node, 'field_role_weight')) {
      $weight = $field[0]['value'];
    }

    $polling_station_nodes[] = array(
      'weight' => $weight,
      'node' => $polling_station_node,
    );
  }

  // Sort callback. 
  $sort_polling_stations = function($a, $b) {
    if ($a['node']->title == $b['node']->title) {
      return 0;
    }

    $result = strnatcmp($b['node']->title, $a['node']->title);
    return $result;
  };

  // Sort callback for weight.
  $sort_polling_stations_weight = function($a, $b) {
    // Skip sorting if no weight is set.
    if ($a['weight'] == 0 || $b['weight'] == 0) {
      return 0;
    }

    if ($a['weight'] == $b['weight']) {
      return 0;
    }

    return ($a['weight'] < $b['weight']) ? -1 : 1;
  };

  // Sort naturally first.
  uasort($polling_station_nodes, $sort_polling_stations);

  // Sort pollingstations according to set weight.
  uasort($polling_station_nodes, $sort_polling_stations_weight);

  foreach ($polling_station_nodes as $data) {
    $polling_station_node = $data['node'];

    $markup .= '<tr><td class="column-first"><a href="/volunteers/station/' . $polling_station_node->nid . '">';
    $markup .= $polling_station_node->title . '</a></td>';

    foreach ($polling_station_count[$polling_station_node->nid]['role_count'] as $role_nid => $role_count) {

      $label = _valhalla_blocks_get_label($role_count);

      $markup .= '<td class="column-count ' . $label . '">'  .    $role_count['total'] . '/' . $role_count['assigned'] . '</td>';
    }

    $label = _valhalla_blocks_get_label($polling_station_count[$polling_station_node->nid]['total_count']);

    $markup .= '<td class="column-count ' . $label . '">'  .  $polling_station_count[$polling_station_node->nid]['total_count']['total'];
    $markup .= '/' . $polling_station_count[$polling_station_node->nid]['total_count']['assigned'] . '</td>';

    $markup .= '</tr>';
  }
  return $markup;
}

/**
 * Helper, find status label.
 */
function _valhalla_blocks_get_label($count) {
  $label = '';
  if ($count['total'] == $count['assigned']) {
    $label = 'warning';
  }
  if ($count['rsvp_ok'] == $count['assigned']) {
    $label = 'success';
  }
  if ($count['rsvp_no']) {
    $label = 'danger';
  }
  return $label;
}
