<?php

/**
 * @file
 * Valghalla_resource_export_service.module.
 */

/**
 * Implements hook_services_resources().
 */
function valghalla_resource_export_service_services_resources() {
  // Include our resources.
  require_once "resources/valghalla_resource_export.inc";

  // Add the resources.
  $resources = array();
  $resources += _valghalla_resource_export_resource_definition();
  return $resources;
}

/**
 * Returns a single node resource as exported node with serialize format.
 *
 * @param mixed $entity
 *   UUID or the whole object of the media we want to return.
 *
 * @return string
 *   Serialized node object or empty array.
 *
 * @see node_export()
 */
function valghalla_resource_export_service_node_get_serialized($entity) {
  $resource = array();
  if (gettype($entity) === 'string') {
    $entity = valghalla_resource_export_service_resource_load($entity);
  }
  if ($entity) {
    // Exporting with serialize formatter.
    $export = node_export(intval($entity->nid), 'serialize');

    if (!empty($export['output'])) {
      $resource = $export['output'];
    }
  }

  // Return the resource.
  return $resource;
}

/**
 * Load a resource provided its uuid.  Much like node_load, but with uuid's...
 *
 * @param mixed $uuid
 *   Uuid of the resource.
 *
 * @return mixed
 *   Loaded node or NULL if nothing is found.
 */
function valghalla_resource_export_service_resource_load($uuid, $reset = FALSE) {
  $nodes = &drupal_static(__FUNCTION__);
  if ($reset || empty($nodes[$uuid])) {
    $entity = entity_uuid_load('node', array($uuid), array(), $reset);
    $nodes[$uuid] = reset($entity);
  }
  return empty($nodes[$uuid]) ? NULL : $nodes[$uuid];
}
