<?php

/**
 * @file
 * Valghalla_external_server_signup.module.
 */

module_load_include('inc', 'valghalla_external_server_signup', 'includes/valghalla_external_server_signup.pages');
module_load_include('inc', 'valghalla_external_server_signup', 'includes/valghalla_external_server_signup.utils');

/**
 * Implements hook_menu().
 */
function valghalla_external_server_signup_menu() {
  $items = array();

  $items['valghalla/external-signup'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('valghalla_external_server_signup_signup_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['valghalla/external-signup-success'] = array(
    'page callback' => '_external_signup_success_page',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/valghalla/settings/external_server_signup'] = array(
    'title' => 'External server signup settings',
    'description' => 'Various setting for external server signup',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('valghalla_external_server_signup_settings_form'),
    'access arguments' => array('administer valghalla'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function valghalla_external_server_signup_theme($existing, $type, $theme, $path) {
  return array(
    'valghalla_external_server_signup_form' => array(
      'render element' => 'form',
      'template' => 'form--valghalla-external-server-signup-form',
      'path' => $path . '/templates',
    ),
  );
}

/**
 * Implements hook_valghalla_allowed_uris_alter().
 */
function valghalla_external_server_signup_valghalla_allowed_uris_alter(&$allowed_uris) {
  $allowed_uris[] = '/valghalla/external-signup*';
}
