<?php

module_load_include('inc', 'valghalla_external_server', 'includes/valghalla_external_server.utils');
module_load_include('inc', 'valghalla_external_server', 'includes/valghalla_external_server.queue');

/**
 * Implement hook_node_insert().
 */
function valghalla_external_server_node_insert($node) {
  if (in_array($node->type, array('volunteers'))) {
    valghalla_synch_queue_add_item($node);
  }
}

/**
 * Implement hook_node_update().
 */
function valghalla_external_server_node_update($node) {
  if (in_array($node->type, array('volunteers'))) {
    valghalla_synch_queue_add_item($node);
  }
}
